```{r setup environment}
library(remotes)
# remotes::install_github("markushuff/PsychHelperFunctions")
library(PsychHelperFunctions)
```

```{r proportion testing}
# === output from rq1_dislike_plot.py
# overall dislike: {'Potentially Prohibited': (85, 0.5, 170), 'Potentially Harmful': (146, 0.49158249158249157, 297), 'Clickbait': (241, 0.4898373983739837, 492), 'Financial': (319, 0.44677871148459386, 714), 'Sensitive': (160, 0.4155844155844156, 385), 'Opportunity': (341, 0.3186915887850467, 1070), 'Healthcare': (292, 0.3109691160809372, 939), 'Benign': (1067, 0.2924088791449712, 3649)}

totals <- c(
    'clickbait' = 492,
    'prohibited' = 170,
    'healthcare' = 939,
    'neutral' = 3649,
    'sensitive' = 385,
    'opportunity' = 1070,    
    'financial' = 714,
    'deceptive' = 297
)

dont_like <- c(
    'clickbait' = 241,
    'prohibited' = 85,
    'deceptive' = 146,
    'sensitive' = 160,
    'financial' = 319,
    'opportunity' = 341,
    'healthcare' = 292,
    'neutral' = 1067
)

p_o=prop.test(
    c(dont_like['clickbait'], dont_like['deceptive'], dont_like['prohibited'],
      dont_like['sensitive'], dont_like['financial'], dont_like['opportunity'],
      dont_like['healthcare'], dont_like['neutral']),
    c(totals['clickbait'], totals['deceptive'], totals['prohibited'],
      totals['sensitive'], totals['financial'], totals['opportunity'],
      totals['healthcare'], totals['neutral'])
)
omnibus_total <- totals['clickbait'] + totals['deceptive'] + totals['prohibited'] +
      totals['sensitive'] + totals['financial'] + totals['opportunity'] +
      totals['healthcare'] + totals['neutral']
# SIGNIFICANT
# Cohen's w
print(paste0("Cohen's w omnibus: ", cohens_w(p_o$statistic, omnibus_total)))

#Pairwise comparisons decreasing sequential
p_1=prop.test(c(dont_like['prohibited'], dont_like['deceptive']), c(totals['prohibited'], totals['deceptive']))
p_2=prop.test(c(dont_like['deceptive'], dont_like['clickbait']), c(totals['deceptive'], totals['clickbait']))
p_3=prop.test(c(dont_like['clickbait'], dont_like['financial']), c(totals['clickbait'], totals['financial']))
p_4=prop.test(c(dont_like['financial'], dont_like['sensitive']), c(totals['financial'], totals['sensitive']))
p_5=prop.test(c(dont_like['sensitive'], dont_like['opportunity']), c(totals['sensitive'], totals['opportunity']))
p_5_total <- totals['sensitive'] + totals['opportunity']
print(paste0("Cohen's w p_5: ", cohens_w(p_5$statistic, p_5_total)))
# SIGNIFICANT 

p_6=prop.test(c(dont_like['opportunity'], dont_like['healthcare']), c(totals['opportunity'], totals['healthcare']))
p_7=prop.test(c(dont_like['healthcare'], dont_like['neutral']), c(totals['healthcare'], totals['neutral']))

#adjusting omnibus and decreasing pairwise comparisons
print("pairwise comparisons decreasing order:")
p.adjust(c(p_o$p.value,p_1$p.value,p_2$p.value,p_3$p.value,p_4$p.value,p_5$p.value,p_6$p.value,p_7$p.value), method="BH" )
print(paste("chi-squared vals:", p_o$statistic, p_1$statistic, p_2$statistic, p_3$statistic, p_4$statistic, p_5$statistic, p_6$statistic, p_7$statistic))


#pairwise comparisons with neutral
p_1=prop.test(c(dont_like['prohibited'], dont_like['neutral']), c(totals['prohibited'], totals['neutral']))
p_1_total <- totals['prohibited'] + totals['neutral']
print(paste0("Cohen's w p_1: ", cohens_w(p_1$statistic, p_1_total)))

p_2=prop.test(c(dont_like['deceptive'], dont_like['neutral']), c(totals['deceptive'], totals['neutral']))
p_2_total <- totals['deceptive'] + totals['neutral']
print(paste0("Cohen's w p_2: ", cohens_w(p_2$statistic, p_2_total)))

p_3=prop.test(c(dont_like['clickbait'], dont_like['neutral']), c(totals['clickbait'], totals['neutral']))
p_3_total <- totals['clickbait'] + totals['neutral']
print(paste0("Cohen's w p_3: ", cohens_w(p_3$statistic, p_3_total)))

p_4=prop.test(c(dont_like['sensitive'], dont_like['neutral']), c(totals['sensitive'], totals['neutral']))
p_4_total <- totals['sensitive'] + totals['neutral']
print(paste0("Cohen's w p_4: ", cohens_w(p_4$statistic, p_4_total)))

p_5=prop.test(c(dont_like['financial'], dont_like['neutral']), c(totals['financial'], totals['neutral']))
p_5_total <- totals['financial'] + totals['neutral']
print(paste0("Cohen's w p_5: ", cohens_w(p_5$statistic, p_5_total)))

p_6=prop.test(c(dont_like['opportunity'], dont_like['neutral']), c(totals['opportunity'], totals['neutral']))
# INSIGNIFICANT
p_6_total <- totals['opportunity'] + totals['neutral']
print(paste0("Cohen's w p_6: ", cohens_w(p_6$statistic, p_6_total)))

p_7=prop.test(c(dont_like['healthcare'], dont_like['neutral']), c(totals['healthcare'], totals['neutral']))
# INSIGNIFICANT
p_7_total <- totals['healthcare'] + totals['neutral']
print(paste0("Cohen's w p_7: ", cohens_w(p_7$statistic, p_7_total)))

#adjusting omnibus and pairwise-with-neutral comparisons
print("pairwise comparisons against neutral:")
p.adjust(c(p_o$p.value,p_1$p.value,p_2$p.value,p_3$p.value,p_4$p.value,p_5$p.value,p_6$p.value,p_7$p.value), method="BH" )
print(paste("chi-squared vals:", p_o$statistic, p_1$statistic, p_2$statistic, p_3$statistic, p_4$statistic, p_5$statistic, p_6$statistic, p_7$statistic))
```